// <auto-generated />
namespace lab_04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202206200355051_updatedatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
